# Generated by Django 3.2.2 on 2022-12-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Place_name', models.CharField(max_length=100)),
                ('place_id', models.CharField(max_length=100)),
                ('reporter_id', models.CharField(max_length=100)),
                ('reporter_name', models.CharField(max_length=100)),
                ('report', models.TextField()),
            ],
        ),
    ]
