# Generated by Django 3.2.2 on 2022-12-17 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('vistingPlaces', models.TextField()),
                ('c_type', models.CharField(max_length=30)),
                ('single_price', models.IntegerField()),
                ('cuple_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TripImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='trip_photos')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tripapp.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripGuider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='tripGuid')),
                ('about', models.TextField()),
                ('location', models.CharField(max_length=99)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('c_type', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField()),
                ('one', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('two', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('three', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('four', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('five', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('trip_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripComp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=50)),
                ('com_img', models.ImageField(upload_to='comp')),
                ('owner_name', models.CharField(max_length=50)),
                ('about_comp', models.TextField()),
                ('one', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('two', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('three', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('four', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('five', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=100)),
                ('c_type', models.CharField(max_length=100)),
                ('single_prics', models.IntegerField(blank=True, null=True)),
                ('cuple_price', models.IntegerField(blank=True, null=True)),
                ('client_name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('chek_in', models.BooleanField()),
                ('chek_out', models.BooleanField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripapp.trip')),
                ('trip_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripapp.tripcomp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_guider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripapp.tripcomp'),
        ),
        migrations.CreateModel(
            name='GuiRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=900)),
                ('one', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('two', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('three', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('four', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('five', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('review', models.CharField(blank=True, max_length=255, null=True)),
                ('guid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='tripapp.tripguider')),
            ],
            options={
                'ordering': ['guid'],
            },
        ),
        migrations.CreateModel(
            name='GuiderBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guider_name', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('c_type', models.CharField(max_length=100)),
                ('single_prics', models.IntegerField(blank=True, null=True)),
                ('cuple_price', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('chek_in', models.BooleanField()),
                ('chek_out', models.BooleanField()),
                ('guider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripapp.tripguider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=900)),
                ('one', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('two', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('three', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('four', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('five', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('review', models.CharField(blank=True, max_length=255, null=True)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='tripapp.tripcomp')),
            ],
            options={
                'ordering': ['comp'],
            },
        ),
    ]
