# Generated by Django 3.2.2 on 2022-12-17 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('hotel_name', models.CharField(max_length=100)),
                ('hotel_description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('security_cameras', models.BooleanField()),
                ('weapons', models.BooleanField()),
                ('dangerous_animals', models.BooleanField()),
                ('one', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('two', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('three', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('four', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('five', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_photo', models.ImageField(default='default.jpg', upload_to='room_photos')),
                ('room_Name', models.CharField(max_length=200)),
                ('room_details', models.CharField(max_length=500)),
                ('max_adults', models.PositiveIntegerField(default=1)),
                ('beds_count', models.PositiveIntegerField(default=1)),
                ('max_child', models.PositiveIntegerField(default=1)),
                ('currency_type', models.CharField(max_length=200)),
                ('extra_beds', models.PositiveIntegerField(default=0)),
                ('extra_bed_price', models.PositiveIntegerField(default=1)),
                ('room_Price', models.PositiveIntegerField(default=1)),
                ('total_Rooms', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('is_conference_room', models.BooleanField(default=False)),
                ('is_apartment', models.BooleanField(default=False)),
                ('free_toiletries', models.BooleanField(default=False)),
                ('water_body_view', models.BooleanField(default=False)),
                ('safe_deposit_box', models.BooleanField(default=False)),
                ('lcd_tv', models.BooleanField(default=False)),
                ('free_wifi', models.BooleanField(default=False)),
                ('pay_tv', models.BooleanField(default=False)),
                ('mini_bar', models.BooleanField(default=False)),
                ('refrigerator', models.BooleanField(default=False)),
                ('blackout_drapes', models.BooleanField(default=False)),
                ('telephone', models.BooleanField(default=False)),
                ('ironing_facilities', models.BooleanField(default=False)),
                ('desk', models.BooleanField(default=False)),
                ('hair_dryer', models.BooleanField(default=False)),
                ('extra_towels', models.BooleanField(default=False)),
                ('bathrobes', models.BooleanField(default=False)),
                ('wake_up_service', models.BooleanField(default=False)),
                ('electric_kettle', models.BooleanField(default=False)),
                ('warddrobe', models.BooleanField(default=False)),
                ('toilet_paper', models.BooleanField(default=False)),
                ('slippers', models.BooleanField(default=False)),
                ('toilet', models.BooleanField(default=False)),
                ('alarm_clock', models.BooleanField(default=False)),
                ('tea_coffee_maker', models.BooleanField(default=False)),
                ('bathtub_shower', models.BooleanField(default=False)),
                ('makeup_shaving_mirror', models.BooleanField(default=False)),
                ('city_view', models.BooleanField(default=False)),
                ('air_conditioner', models.BooleanField(default=False)),
                ('cribs_infant_beds', models.BooleanField(default=False)),
                ('daily_housekeeping', models.BooleanField(default=False)),
                ('garden_view', models.BooleanField(default=False)),
                ('projector', models.BooleanField(default=False)),
                ('screen', models.BooleanField(default=False)),
                ('conference_phone', models.BooleanField(default=False)),
                ('water', models.BooleanField(default=False)),
                ('speakers', models.BooleanField(default=False)),
                ('whiteboard', models.BooleanField(default=False)),
                ('sockets', models.BooleanField(default=False)),
                ('coffee', models.BooleanField(default=False)),
                ('monitors', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hotel')),
            ],
            options={
                'ordering': ['room_Price', 'updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='room_photos')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.room')),
            ],
            options={
                'verbose_name_plural': 'Room Photos',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=900)),
                ('one', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('two', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('three', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('four', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('five', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('review', models.CharField(blank=True, max_length=255, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='home.hotel')),
            ],
            options={
                'ordering': ['hotel'],
            },
        ),
        migrations.CreateModel(
            name='HotelImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='hotels')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.hotel')),
            ],
            options={
                'verbose_name_plural': 'Hotel Photos',
            },
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('room_name', models.CharField(max_length=100)),
                ('hotel_name', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('chek_in', models.BooleanField()),
                ('chek_out', models.BooleanField()),
                ('c_type', models.CharField(max_length=100)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hotel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Hotel_bookings', to='home.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
