# Generated by Django 3.2.2 on 2022-12-17 08:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privecypolicy',
            name='content',
        ),
        migrations.AlterField(
            model_name='privecypolicy',
            name='privaceypolicy',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
