# Generated by Django 3.2.2 on 2022-12-17 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('house_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('guests', models.IntegerField()),
                ('bed_count', models.IntegerField()),
                ('room_count', models.IntegerField(default=10)),
                ('bathroom_count', models.IntegerField()),
                ('security_cameras', models.BooleanField()),
                ('weapons', models.BooleanField()),
                ('dangerous_animals', models.BooleanField()),
                ('c_type', models.CharField(blank=True, max_length=20, null=True)),
                ('house_price', models.IntegerField()),
                ('is_apartment', models.BooleanField(default=False)),
                ('free_wifi', models.BooleanField(default=False)),
                ('refrigerator', models.BooleanField(default=False)),
                ('telephone', models.BooleanField(default=False)),
                ('ironing_facilities', models.BooleanField(default=False)),
                ('wake_up_service', models.BooleanField(default=False)),
                ('electric_kettle', models.BooleanField(default=False)),
                ('tea_coffee_maker', models.BooleanField(default=False)),
                ('daily_housekeeping', models.BooleanField(default=False)),
                ('city_view', models.BooleanField(default=False)),
                ('one', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('two', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('three', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('four', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('five', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HouseModel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_photo', models.ImageField(default='default.jpg', upload_to='room_photos')),
                ('room_Name', models.CharField(max_length=200)),
                ('room_details', models.CharField(max_length=500)),
                ('max_adults', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('free_toiletries', models.BooleanField(default=False)),
                ('safe_deposit_box', models.BooleanField(default=False)),
                ('lcd_tv', models.BooleanField(default=False)),
                ('pay_tv', models.BooleanField(default=False)),
                ('mini_bar', models.BooleanField(default=False)),
                ('blackout_drapes', models.BooleanField(default=False)),
                ('desk', models.BooleanField(default=False)),
                ('hair_dryer', models.BooleanField(default=False)),
                ('extra_towels', models.BooleanField(default=False)),
                ('bathrobes', models.BooleanField(default=False)),
                ('warddrobe', models.BooleanField(default=False)),
                ('toilet_paper', models.BooleanField(default=False)),
                ('slippers', models.BooleanField(default=False)),
                ('toilet', models.BooleanField(default=False)),
                ('alarm_clock', models.BooleanField(default=False)),
                ('bathtub_shower', models.BooleanField(default=False)),
                ('makeup_shaving_mirror', models.BooleanField(default=False)),
                ('air_conditioner', models.BooleanField(default=False)),
                ('garden_view', models.BooleanField(default=False)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.house')),
            ],
            options={
                'ordering': ['room_Name', 'updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='room_photos')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='house.room')),
            ],
            options={
                'verbose_name_plural': 'Room Photos',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=900)),
                ('one', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('two', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('three', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('four', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('five', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('review', models.CharField(blank=True, max_length=255, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='house.house')),
            ],
            options={
                'ordering': ['house'],
            },
        ),
        migrations.CreateModel(
            name='HouseImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('images', models.ImageField(upload_to='house')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='House_images', to='house.house')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HouseBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('chek_in', models.BooleanField()),
                ('chek_out', models.BooleanField()),
                ('c_type', models.CharField(max_length=100)),
                ('prics', models.IntegerField(blank=True, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.house')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
